### ISSUE TITLE
全屏似乎有点问题，而且没有打开文章没有目录，如何修改？

### ISSUE THREAD

**Issue by Pai-Po** [fengxianqi/7TEC#1]
![image](https://user-images.githubusercontent.com/12437819/60502809-07988c00-9cf1-11e9-8ddb-2da09cf1bb3d.png)

**Comment by fengxianqi** [comment]
感谢反馈，目录是在后台管理中设置的分类。全屏的问题是由于文章数量较少，高度不足以撑高到全屏，这个问题后续会优化一下，紧急的话可以加一个样式暂时解决: #body{ min-height: 100vh; }

**Comment by Pai-Po** [comment]
嗯。好的，谢谢。主题很不错
